-- MySQL Script generated by MySQL Workbench
-- Fri Jul  7 14:09:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ac_wpn_db
-- -----------------------------------------------------
-- 微信公众号数据库

-- -----------------------------------------------------
-- Schema ac_wpn_db
--
-- 微信公众号数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ac_wpn_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ac_wpn_db` ;

-- -----------------------------------------------------
-- Table `ac_wpn_db`.`WxPublicNumber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ac_wpn_db`.`WxPublicNumber` ;

CREATE TABLE IF NOT EXISTS `ac_wpn_db`.`WxPublicNumber` (
  `wxPublicNumberId` BIGINT NOT NULL AUTO_INCREMENT COMMENT '公众号编号',
  `appId` VARCHAR(128) NOT NULL COMMENT '公众号应用编号',
  `secret` VARCHAR(128) NOT NULL COMMENT '公众号密钥',
  `name` VARCHAR(128) NOT NULL COMMENT '公众号名称',
  `token` VARCHAR(128) NULL COMMENT '回调地址验证token',
  `primaryndustry` VARCHAR(8) NULL,
  `secondaryndustry` VARCHAR(8) NULL,
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`wxPublicNumberId`),
  UNIQUE INDEX `secret_UNIQUE` (`secret` ASC),
  UNIQUE INDEX `appId_UNIQUE` (`appId` ASC))
ENGINE = InnoDB
COMMENT = '微信公众号';


-- -----------------------------------------------------
-- Table `ac_wpn_db`.`WxPublicNumberUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ac_wpn_db`.`WxPublicNumberUser` ;

CREATE TABLE IF NOT EXISTS `ac_wpn_db`.`WxPublicNumberUser` (
  `userId` BIGINT NOT NULL AUTO_INCREMENT COMMENT '微信绑定用户编号',
  `openid` VARCHAR(64) NOT NULL COMMENT '微信用户编号',
  `unionid` VARCHAR(64) NULL COMMENT '微信用户唯一编号',
  `appId` VARCHAR(128) NOT NULL COMMENT '公众号应用编号',
  `authUserInfo` TEXT NULL COMMENT '授权用户详细信息',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`userId`))
ENGINE = InnoDB
COMMENT = '微信绑定用户详情';


-- -----------------------------------------------------
-- Table `ac_wpn_db`.`WxBindUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ac_wpn_db`.`WxBindUser` ;

CREATE TABLE IF NOT EXISTS `ac_wpn_db`.`WxBindUser` (
  `bindUserId` BIGINT NOT NULL AUTO_INCREMENT COMMENT '绑定用户编号',
  `userId` BIGINT NOT NULL COMMENT '微信用户编号',
  `partyId` VARCHAR(16) NULL COMMENT '机构号',
  `userName` VARCHAR(16) NULL COMMENT '用户名',
  `bindType` CHAR(2) NOT NULL COMMENT '绑定类型',
  `status` CHAR(1) NOT NULL COMMENT '绑定状态',
  `bindAttrs` TEXT NULL COMMENT '绑定参数',
  `createTime` VARCHAR(45) NOT NULL COMMENT '创建时间',
  `updateTime` VARCHAR(45) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`bindUserId`))
ENGINE = InnoDB
COMMENT = '绑定用户';


-- -----------------------------------------------------
-- Table `ac_wpn_db`.`WxMessageTemplate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ac_wpn_db`.`WxMessageTemplate` ;

CREATE TABLE IF NOT EXISTS `ac_wpn_db`.`WxMessageTemplate` (
  `wxMessageTemplateId` BIGINT NOT NULL AUTO_INCREMENT,
  `templateName` VARCHAR(128) NOT NULL COMMENT '模板消息编号',
  `appAlais` VARCHAR(128) NOT NULL COMMENT '微信公众号编号',
  `messageTemplateGroupId` BIGINT NOT NULL DEFAULT 0 COMMENT '分组编号',
  `templateDesc` TEXT NOT NULL COMMENT '模板描述',
  `weixinTemplateId` VARCHAR(128) NOT NULL COMMENT '微信模板编号',
  `paramConfigs` VARCHAR(512) NOT NULL,
  `url` VARCHAR(256) NULL COMMENT '链接地址',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` VARCHAR(45) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`wxMessageTemplateId`),
  UNIQUE INDEX `templateName_applais_index` (`templateName` ASC, `appAlais` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ac_wpn_db`.`WeixinQRCode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ac_wpn_db`.`WeixinQRCode` ;

CREATE TABLE IF NOT EXISTS `ac_wpn_db`.`WeixinQRCode` (
  `weixinQRCodeId` BIGINT NOT NULL AUTO_INCREMENT COMMENT '二维码编号',
  `sceneId` VARCHAR(64) NOT NULL COMMENT '场景编号',
  `qrCodeType` VARCHAR(8) NOT NULL COMMENT '二维码类型',
  `paramJson` VARCHAR(1024) NULL COMMENT '二维码参数',
  `ticket` VARCHAR(256) NOT NULL COMMENT '二维码票据',
  `qrCodeShortUrl` VARCHAR(32) NOT NULL COMMENT '短连接',
  `qrCodeBizType` CHAR(2) NOT NULL COMMENT '业务类型',
  `appId` VARCHAR(128) NOT NULL COMMENT '公众号',
  `qrCodeContent` VARCHAR(256) NOT NULL,
  `traceNo` VARCHAR(64) NULL,
  `expireSeconds` BIGINT NULL,
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`weixinQRCodeId`),
  INDEX `sceneId_index` (`sceneId` ASC),
  INDEX `traceNo_qrCodeBizType_index` (`qrCodeBizType` ASC, `traceNo` ASC))
ENGINE = InnoDB
COMMENT = '微信二维码';


-- -----------------------------------------------------
-- Table `ac_wpn_db`.`WeixinNotifyInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ac_wpn_db`.`WeixinNotifyInfo` ;

CREATE TABLE IF NOT EXISTS `ac_wpn_db`.`WeixinNotifyInfo` (
  `weixinNotifyInfoId` BIGINT NOT NULL AUTO_INCREMENT,
  `appId` VARCHAR(128) NOT NULL COMMENT '公众号',
  `messageHashCode` VARCHAR(128) NOT NULL COMMENT '消息散列值',
  `notifyContent` TEXT NULL,
  `sign` VARCHAR(128) NOT NULL COMMENT '消息签名信息',
  `dealStatus` CHAR(1) NOT NULL COMMENT '处理状态',
  `dealResultDesc` VARCHAR(512) NULL COMMENT '处理描述信息',
  `receiveTime` DATETIME NOT NULL COMMENT '接收时间',
  `updateTime` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`weixinNotifyInfoId`))
ENGINE = InnoDB
COMMENT = '微信通知消息信息';


-- -----------------------------------------------------
-- Table `ac_wpn_db`.`WxBindCardHolder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ac_wpn_db`.`WxBindCardHolder` ;

CREATE TABLE IF NOT EXISTS `ac_wpn_db`.`WxBindCardHolder` (
  `wxBindCardHolderId` BIGINT NOT NULL AUTO_INCREMENT COMMENT '微信绑定信息编号',
  `cardNOToken` VARCHAR(64) NOT NULL COMMENT '卡号令牌编号',
  `userId` BIGINT NOT NULL COMMENT '用户编号',
  `bindStatus` CHAR(1) NOT NULL COMMENT '绑定状态',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  `updateTime` DATETIME NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`wxBindCardHolderId`))
ENGINE = InnoDB
COMMENT = '持卡人绑定信息';


-- -----------------------------------------------------
-- Table `ac_wpn_db`.`MessageSwitchConfig`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ac_wpn_db`.`MessageSwitchConfig` ;

CREATE TABLE IF NOT EXISTS `ac_wpn_db`.`MessageSwitchConfig` (
  `messageSwitchConfigId` BIGINT NOT NULL AUTO_INCREMENT COMMENT '开关编号',
  `open` TINYINT(1) NOT NULL COMMENT '是否打开',
  `target` VARCHAR(32) NOT NULL COMMENT '开关目标对象',
  `targetType` CHAR(1) NOT NULL COMMENT '开关目标对象类型',
  `messageTemplateGroupId` BIGINT NOT NULL COMMENT '消息组编号',
  `createTime` DATETIME NOT NULL,
  PRIMARY KEY (`messageSwitchConfigId`),
  INDEX `messageTemplateGroupId_index` (`messageTemplateGroupId` ASC)  COMMENT '消息组索引')
ENGINE = InnoDB
COMMENT = '消息开关配置';


-- -----------------------------------------------------
-- Table `ac_wpn_db`.`MessageTemplateGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ac_wpn_db`.`MessageTemplateGroup` ;

CREATE TABLE IF NOT EXISTS `ac_wpn_db`.`MessageTemplateGroup` (
  `messageTemplateGroupId` BIGINT NOT NULL AUTO_INCREMENT COMMENT '消息组编号',
  `groupName` VARCHAR(256) NOT NULL COMMENT '消息组名称',
  `appId` VARCHAR(16) NOT NULL COMMENT '所属应用',
  `priority` INT NOT NULL COMMENT '优先级',
  `createTime` DATETIME NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`messageTemplateGroupId`))
ENGINE = InnoDB
COMMENT = '消息组';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
